#+Title:夜猫SRPG

* 介绍
夜猫SRPG是为个人正在开发的游戏《夜之城传说》定制的一套SRPG模板，该模板包含的功能包括：回合管理、阶段菜单管理、单位和行动的选择、远端多人回合制支持。
本人也是找不到合适的SRPG模板才会自己制作这样一套模板，希望在完成自己项目的同时，帮助更多想用godot制作SRPG的用户快速建立自己的SRPG项目，该模板借用用的插件和素材的 *credit* 都包含在了 *license* 文件夹中。
除了本项目借用素材部分外的其它个人开发部分，均以《创作者共享协议》和《程序员共享协议》发布，具体协议文本见根目录的License页面。

* 文档
本项目的文档手册都在docs分支，如果有需要可以自行阅览。

* 阶段管理器
本项目的阶段管理器(PhaseController)有一套独特的context上下文机制，该机制会在每个phase的_enter()方法中自动调用一个方法来将本phase的上下文传递给下一个phase，因此在phase中对上下文进行操作是常见的操作方式，目前已用到的上下文详见文档。
原则上，上下文尽量不要用Object和节点类型，如果需要在上下文中引用Object对象或者节点类型，请用字典或NodePath替代。

* 命令调度机制
本项目通过CommandBus单例调度命令的形式来传递命令，通常对menumanager节点和gamephasemanager节点的操作都以命令为主调度。
不同的是menumanager的命令一般是在本地调度，而gamephasemanager的命令是在服务端调度。

* 单位与行动
本项目的主要执行逻辑以单位和行动为主，一切在网格棋盘上的都是继承自单位对象，单位具备基本的网格移动属性。
而行动则是character对象特有的属性，一切character对象的交互，都是行动的一种。

interactable对象的交互则是例外，interactable对象目前调用的是更底层的方法，而非行动。

* 多人机制
本项目的多人机制，通过rpc调用命令的方式为实现，具体原理是将gamephasemanager作为只在服务端运行的调度中心，客户端不会启动gamephasemanager，行动的执行、菜单的激活都gamephasemanager来进行rpc调用实现。

而菜单的选项则是给服务端的gamephasemanager调用发送命令来实现客户端与服务端的通信。

目前多人机制默认是多个玩家轮流执行行动，根据part来决定激活哪个客户端的行动选择菜单。

本项目默认不同步属性，而是通过同步rpc调用的方法，通过客户端执行行动的逻辑，来达成服务端和客户端一样的效果。
