#+TITLE: 怪盗莺猫传 - 程序规范
* 分支结构
** main分支
主分支，用于稳定和正式上线的版本。
从release分支合并到mian分支后，需要用git tag命令给main分支标记新的版本号。
** develop分支
开发分支，用于最新特性版本的开发，所有其它分支都会合并到该分支。
若需要测试发布该分支的版本，则需要先从该分支分出一个release分支进行测试
** nightcat分支
用于游戏基础模板的分支，与游戏模板相关的feature更新到此分支。
** nightgame分支
用于游戏内容的分支，制作游戏的剧情、关卡、单位、ai等部分的内容都在此分支进行开发。
** gameworks分支
游戏项目档案分支，用于同步更新游戏项目相关内容。
** docs分支
文档分支，用于维护程序文档、规范、使用手册等。
** release/分支
发布前的测试分支，用于测试版本并合并到main分支，合并后需要使用git tag命令给main分支标记新的版本号。
** feature/分支
从develop分出，用于开发新功能的分支，该分支应该包含确定性高且已经过严格的原型测试的玩法，feature分支完成后应尽快合并。
feature分支的项目应该以高可维护性的代码为主。
** prototype/分支
从develop分出，用于测试游戏原型的分支，该分支通常无需合并，仅用于原型测试。
所有预想的游戏机制、玩法、关卡设计等，在实装之前，都必须在该分支完成测试再通过feature分支实装。
此外，该分支的目的应该以消除不确定性为主，因此通过该分支测试出来还是有较大不确定性的原型不适合通过feature分支实装。
prototype分支的所有项目应该以快速迭代为主。
** fix/分支
从develop分出，用于修复bug和优化程序的分支。
** hotfix/分支
从main分出，用于紧急修复程序上线后存在的bug的分支，合并回main分支需要给main分支标记新的版本号。

* 注释规范
** 函数注释
每个函数都应该注释其用途以及使用方法，以便其它参与者使用。

** 待办注释
所有与bug修复相关的待办，比如BUG，应当注释在出问题的方法上面，例：
#+BEGIN_SRC gdscript
# BUG: 当输入为空时会发生错误，需要增加输入验证
func process(data):
    # ...
    pass
#+END_SRC

所有宏观规划层面的待办，则应写在项目根目录的todo.org文件的对应条目中,例：
#+BEGIN_SRC org
 * TODO 实现物品机制。
#+END_SRC

与功能实现相关的更具体的规划的待办，则可以写在相关类的开头，例:
#+BEGIN_SRC gdscript
# TODO：为背包添加首字母搜索功能。
class_name Inventory
#+END_SRC
